-- 1ere question:

CREATE TABLE SPORTIFS (
    IDSPORTIF INT PRIMARY KEY,
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(50) NOT NULL,
    SEXE CHAR(1) CHECK (SEXE IN ('M', 'F')),
    AGE INT CHECK (AGE >= 0),
    IDSPORTIFCONSEILLER INT,
    FOREIGN KEY (IDSPORTIFCONSEILLER) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE SET NULL
);

CREATE TABLE SPORTS (
    IDSPORT INT PRIMARY KEY,
    LIBELLE VARCHAR(100) NOT NULL
);

CREATE TABLE GYMNASES (
    IDGYMNASE INT PRIMARY KEY,
    NOMGYMNASE VARCHAR(100) NOT NULL,
    ADRESSE VARCHAR(255) NOT NULL,
    VILLE VARCHAR(100) NOT NULL,
    SURFACE INT CHECK (SURFACE > 0)
);

CREATE TABLE ARBITRER (
    IDSPORTIF INT,
    IDSPORT INT,
    PRIMARY KEY (IDSPORTIF, IDSPORT),
    FOREIGN KEY (IDSPORTIF) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE
);

CREATE TABLE ENTRAINER (
    IDSPORTIFENTRAINEUR INT,
    IDSPORT INT,
    PRIMARY KEY (IDSPORTIFENTRAINEUR, IDSPORT),
    FOREIGN KEY (IDSPORTIFENTRAINEUR) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE
);

CREATE TABLE JOUER (
    IDSPORTIF INT,
    IDSPORT INT,
    PRIMARY KEY (IDSPORTIF, IDSPORT),
    FOREIGN KEY (IDSPORTIF) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE
);

CREATE TABLE SEANCES (
    IDGYMNASE INT,
    IDSPORT INT,
    IDSPORTIFENTRAINEUR INT,
    JOUR VARCHAR(10) CHECK (JOUR IN ('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche')),
    HORAIRE NUMBER CHECK (HORAIRE >= 0 AND HORAIRE < 24),
    DUREE INT CHECK (DUREE > 0),
    PRIMARY KEY (IDGYMNASE, IDSPORT, IDSPORTIFENTRAINEUR, JOUR, HORAIRE),
    FOREIGN KEY (IDGYMNASE) REFERENCES GYMNASES(IDGYMNASE) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORTIFENTRAINEUR) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE
);




-- 2eme question:
Alter TABLE GYMNASES
ADD DATECREATION Date;





-- 3eme question:
ALTER TABLE SPORTIFS
MODIFY SEXE Char(1) NOT NULL;
ALTER TABLE SPORTIFS
MODIFY AGE INT NOT NULL;




-- 4eme question:
ALTER TABLE SPORTIFS
MODIFY PRENOM VARCHAR(70);
ALTER TABLE SPORTIFS
MODIFY PRENOM VARCHAR(50);





-- 5eme question:
ALTER TABLE GYMNASES
DROP COLUMN DATECREATION;




-- 6eme question:
ALTER TABLE GYMNASES
RENAME COLUMN ADRESSE TO ADRESSEGYM;
-- Verification
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'GYMNASES';




-- 7eme question:
ALTER TABLE SPORTS 
ADD CONSTRAINT ck_libelle 
CHECK (LIBELLE IN ('Basket ball', 'Volley ball', 'Hockey', 'Hand ball', 'Tennis', 'Badmington', 'Ping pong', 'Boxe', 'Football'));




-- 8eme question c l'insertion du fichier insert.sql



-- 9eme question:
UPDATE SPORTIFS 
SET IDSPORTIFCONSEILLER = (SELECT IDSPORTIF FROM SPORTIFS WHERE NOM = 'CHAADI' AND PRENOM = 'Mourad') 
WHERE NOM = 'LACHEMI' AND PRENOM = 'Bouzid';





-- 10eme question:
ALTER TABLE SPORTS 
DISABLE CONSTRAINT ck_libelle;

INSERT INTO SPORTS (IDSPORT, LIBELLE) VALUES (10, 'Natation');
INSERT INTO SPORTS (IDSPORT, LIBELLE) VALUES (11, 'Golf');

ALTER TABLE SPORTS 
ENABLE CONSTRAINT ck_libelle;
ALTER TABLE SPORTS 
DROP CONSTRAINT ck_libelle;
ALTER TABLE SPORTS 
ADD CONSTRAINT ck_libelle 
CHECK (LIBELLE IN ('Basket ball', 'Volley ball', 'Hockey', 'Hand ball', 
                   'Tennis', 'Badmington', 'Ping pong', 'Boxe', 'Football', 
                   'Natation', 'Golf'));




-- 11eme question:
DELETE FROM SEANCES 
WHERE IDGYMNASE IN (SELECT IDGYMNASE FROM GYMNASES WHERE SURFACE > 400);
DELETE FROM GYMNASES 
WHERE SURFACE > 400;


-- 12eme question:
SELECT IDSPORTIF, NOM, PRENOM 
FROM SPORTIFS 
WHERE AGE BETWEEN 20 AND 30;




-- 13eme question:
SELECT DISTINCT IDSPORTIF, NOM, PRENOM 
FROM SPORTIFS 
WHERE IDSPORTIF IN (SELECT IDSPORTIFCONSEILLER FROM SPORTIFS WHERE IDSPORTIFCONSEILLER IS NOT NULL);




-- 14eme question:
SELECT S.IDSPORTIF, S.NOM, S.PRENOM
FROM SPORTIFS S
WHERE S.IDSPORTIF IN (
    SELECT E.IDSPORTIFENTRAINEUR
    FROM ENTRAINER E
    JOIN SPORTS SP ON E.IDSPORT = SP.IDSPORT
    GROUP BY E.IDSPORTIFENTRAINEUR
    HAVING COUNT(DISTINCT SP.LIBELLE) = 2 
           AND SUM(CASE WHEN SP.LIBELLE NOT IN ('Hand ball', 'Basket ball') THEN 1 ELSE 0 END) = 0
);




-- 15eme question:
SELECT IDSPORTIF, NOM, PRENOM, AGE
FROM SPORTIFS 
WHERE AGE = (SELECT MIN(AGE) FROM SPORTIFS);




-- 16eme question:
