CREATE TABLE SPORTIFS (
    IDSPORTIF INT PRIMARY KEY,
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(50) NOT NULL,
    SEXE CHAR(1) CHECK (SEXE IN ('M', 'F')),
    AGE INT CHECK (AGE >= 0),
    IDSPORTIFCONSEILLER INT,
    FOREIGN KEY (IDSPORTIFCONSEILLER) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE SET NULL
);

CREATE TABLE SPORTS (
    IDSPORT INT PRIMARY KEY,
    LIBELLE VARCHAR(100) NOT NULL
);

CREATE TABLE GYMNASES (
    IDGYMNASE INT PRIMARY KEY,
    NOMGYMNASE VARCHAR(100) NOT NULL,
    ADRESSE VARCHAR(255) NOT NULL,
    VILLE VARCHAR(100) NOT NULL,
    SURFACE INT CHECK (SURFACE > 0)
);

CREATE TABLE ARBITRER (
    IDSPORTIF INT,
    IDSPORT INT,
    PRIMARY KEY (IDSPORTIF, IDSPORT),
    FOREIGN KEY (IDSPORTIF) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE
);

CREATE TABLE ENTRAINER (
    IDSPORTIFENTRAINEUR INT,
    IDSPORT INT,
    PRIMARY KEY (IDSPORTIFENTRAINEUR, IDSPORT),
    FOREIGN KEY (IDSPORTIFENTRAINEUR) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE
);

CREATE TABLE JOUER (
    IDSPORTIF INT,
    IDSPORT INT,
    PRIMARY KEY (IDSPORTIF, IDSPORT),
    FOREIGN KEY (IDSPORTIF) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE
);

CREATE TABLE SEANCES (
    IDGYMNASE INT,
    IDSPORT INT,
    IDSPORTIFENTRAINEUR INT,
    JOUR VARCHAR(10) CHECK (JOUR IN ('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche')),
    HORAIRE NUMBER CHECK (HORAIRE >= 0 AND HORAIRE < 24),
    DUREE INT CHECK (DUREE > 0),
    PRIMARY KEY (IDGYMNASE, IDSPORT, IDSPORTIFENTRAINEUR, JOUR, HORAIRE),
    FOREIGN KEY (IDGYMNASE) REFERENCES GYMNASES(IDGYMNASE) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE,
    FOREIGN KEY (IDSPORTIFENTRAINEUR) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE
);
