--1
CONNECT ing/psw;
--2
CREATE USER USERFOUR IDENTIFIED BY psw1 DEFAULT TABLESPACE Livraison_TBS TEMPORARY TABLESPACE Livraison_TempTBS;
ALTER USER USERFOUR ACCOUNT UNLOCK;

CONNECT system/131004;
DESC dba_users;
SELECT username, created FROM dba_users WHERE username='USERFOUR';
CONNECT userfour/psw1;
--3
CONNECT ing/psw;
GRANT CREATE SESSION TO USERFOUR WITH ADMIN OPTION;
CONNECT system/psw;
DESC dba_sys_privs;
SELECT privilege, admin_option FROM dba_sys_privs WHERE grantee='USERFOUR';
CONNECT userfour/psw1;
SELECT privilege, admin_option FROM user_sys_privs;
--4
CONNECT ing/psw;
GRANT CREATE TABLE, CREATE VIEW TO USERFOUR;
CREATE TABLE test (a NUMBER, b VARCHAR2(1));
ALTER USER USERFOUR QUOTA 10M ON LIVRAISON_TBS;
CREATE TABLE test (a NUMBER, b VARCHAR2(1));
SELECT table_name FROM user_tables;
INSERT INTO test VALUES (1, 'b');
SELECT * FROM test;
SELECT object_name, object_type FROM user_objects;
CREATE VIEW view1 AS SELECT a FROM test;
-- 5
GRANT SELECT ON fournisseur1 TO USERFOUR;
CONNECT userfour/psw1;
SELECT * FROM ing.fournisseur1;
--6
CONNECT ing/psw;

CREATE TABLE usine1 (NU NUMBER PRIMARY KEY, NomU VARCHAR2(15), Ville VARCHAR2(15));


CREATE TABLE produit1 (
    np NUMBER PRIMARY KEY,
    nomp VARCHAR2(20),
    couleur VARCHAR2(10),
    poids FLOAT CHECK (poids>0)
);


CREATE TABLE livraison1 (
    np NUMBER,
    nu NUMBER,
    nf NUMBER,
    quantite NUMBER CHECK (quantite>0),
    CONSTRAINT pk_livraison1 PRIMARY KEY (np, nu, nf),
    CONSTRAINT fk_livraison1_prod FOREIGN KEY (np) REFERENCES produit1(np) ON DELETE CASCADE,
    CONSTRAINT fk_livraison1_usin FOREIGN KEY (nu) REFERENCES usine1(nu) ON DELETE CASCADE
);


INSERT INTO usine1 VALUES (1, 'Citroen', 'Paris');
INSERT INTO produit1 VALUES (1, 'Plaquette', 'Noir', 0.257);
INSERT INTO livraison1 VALUES (1, 2, 3, 2500);

GRANT DELETE ON produit1 TO USERFOUR;
GRANT SELECT, DELETE ON livraison1 TO USERFOUR;
CONNECT userfour/psw1;
DELETE FROM produit1 WHERE NOT EXISTS (SELECT 1 FROM livraison1 WHERE livraison1.np = produit1.np);
--7
CONNECT ing/psw;
GRANT CREATE INDEX TO USERFOUR;
CONNECT userfour/psw1;
CREATE INDEX ind_nf ON ing.fournisseur1 (nomf);
--8
CREATE PROFILE USERFOUR_Profil LIMIT
    SESSIONS_PER_USER 4 CONNECT_TIME 70 IDLE_TIME 20 CPU_PER_CALL 30000;
ALTER USER USERFOUR PROFILE USERFOUR_Profil;
CONNECT system/29112004;
SELECT username, profile FROM dba_users WHERE username = 'USERFOUR';
--9
CONNECT ing/psw;
CREATE ROLE GESTION_LIVRAISON;
GRANT SELECT ON fournisseur1 TO GESTION_LIVRAISON;
GRANT DELETE, SELECT, INSERT, UPDATE ON livraison1 TO GESTION_LIVRAISON;
GRANT GESTION_LIVRAISON TO USERFOUR;
SELECT privilege FROM role_sys_privs WHERE role = 'GESTION_LIVRAISON';

SELECT owner, table_name, privilege FROM role_tab_privs WHERE role = 'GESTION_LIVRAISON';
CONNECT userfour/psw1;
SELECT * FROM user_tab_privs WHERE grantee = 'USERFOUR';
--15 
CONNECT ing/psw;
SELECT table_name FROM user_tables;
CONNECT system/29112004;
SELECT table_name FROM dba_tables WHERE owner='ING';
--16
SELECT COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLUMNS WHERE TABLE_NAME IN ('PRODUIT', 'LIVRAISON');
--17
SELECT UC.CONSTRAINT_NAME, UCC.COLUMN_NAME FROM USER_CONSTRAINTS UC JOIN USER_CONS_COLUMNS UCC ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME WHERE UC.CONSTRAINT_TYPE = 'R' AND UC.TABLE_NAME = 'PRODUIT';
--18
SELECT CONSTRAINT_NAME, TABLE_NAME FROM USER_CONSTRAINTS;
--19
GRANT CONNECT TO USERFOUR;
GRANT SELECT ON fournisseur TO USERFOUR;
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE = 'USERFOUR';
--21
CREATE ROLE ROLE_GESTION;
GRANT SELECT, UPDATE ON fournisseur TO ROLE_GESTION;
--22
GRANT ROLE_GESTION TO USERFOUR;
SELECT * FROM USER_ROLE_PRIVS WHERE GRANTEE = 'USERFOUR';
SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS;
--23
SELECT OWNER FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'FOURNISSEUR';
--24
SELECT INSTANCE_NAME, VERSION, STATUS FROM V$INSTANCE;
--25
SELECT NAME, OPEN_MODE FROM V$DATABASE;
--26
SELECT * FROM V$SGA;
SELECT NAME, BYTES FROM V$SGASTAT;
--27
SELECT MEMBER FROM V$LOGFILE;
--28
SELECT FILE_NAME, BLOCK_SIZE FROM V$DATAFILE;
--29
SELECT TABLESPACE_NAME FROM V$TABLESPACE;
--30
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
